### ISSUE TITLE
Missing space after parenthesis doesn't error when using multi line parameters

### ISSUE THREAD

**Issue by jrmd** [bigbite/phpcs-config#119]
**Describe the bug**  
Multi line function calls seem to ignore the requirement for a space after the open parens

**To Reproduce**  
Create a function call that takes multiple parameters

```php
<?php

register_post_meta('post', 'article_standfirst',
	[
		'type'          => 'string',
		'description'   => __( 'article standfirst', 'multi-title' ),
		'auth_callback' => function() {
			return current_user_can( 'edit_posts' );
		},
		'single'        => true,
		'show_in_rest'  => true,
	]
);
```

**Expected behaviour**  
I expect PHPCS to error saying that there is a missing space after the opening bracket

**Platform**  
- OS: macOS & CircleCI
- Shell: ZSH

**Comment by jrmd** [comment]
Tested this on the release/v2.0.0 branch and it works there

**Comment by jonmcp** [comment]
I think this is because the Sniff that covers function call signatures (`PEAR.Functions.FunctionCallSignature`) expects multiline function calls to look like this:
```php
register_post_meta(
	'post',
	'article_standfirst',
	[
		'type'          => 'string',
		'description'   => __( 'article standfirst', 'multi-title' ),
		'auth_callback' => function () {
			return current_user_can( 'edit_posts' );
		},
		'single'        => true,
		'show_in_rest'  => true,
	]
);
```

The Sniff expects the opening parens to be the last token on the line, each argument to be on its own line, and the closing paren to be on its own line. But, something is preventing it from reporting on that in this specific case. I'll do some deeper digging.

**Comment by jonmcp** [comment]
The sniff expects either:
- a single line function call, in which case it performs the whitespace check; or
- a multiline function call, in which case it expects no content after the opening paren, or before the closing paren

However, we silence the multiline error, to allow for nicer callbacks in actions and filters. So this is less a failing of the sniff, and more a failing in our expectations, because our expectations are:
- in a single-line function call, place whitespace between arguments and the opening/closing parens
- in a multi-line function call, allow args on the same lines as the opening/closing parens "where it makes sense", as long as there is whitespace between the args and opening/closing parens

But it is difficult for a sniff to make assumptions about where it is acceptable for multiline function calls to place its arguments.

So, we generally prefer this format:
```php

foo( 'bar' );

foo( 'bar', 'baz' );

add_action( 'bar', function () {
    // do something
}, 10, 2 );

register_rest_route( 'foo, 'bar', [
    // args
] );

register_rest_route(
    'foo',
    'bar',
    [
        // args
    ]
);
```

This is inconsistent, and sniffs are not designed to allow for inconsistencies - it's somewhat against the entire principle of linting tools in general! - so it fails in this case.
